# Array Indexing
1. Integer Indexing
2. Boolean Indexing

## Integer Indexing

In [1]:
# Initialize variables

import numpy as np 

list1 = [1,1.1,-5.45,3.2]
arr1 = np.array(list1)

list2 = [[1,1.1,-5.45,3.2],[-0.5,0.33,10.12,-5]]
arr2 = np.array(list2)

In [2]:
# 1d arrays are similar to python lists
print (arr1[0])
print (arr1[1:3])
print (arr1[-2:])

1.0
[ 1.1  -5.45]
[-5.45  3.2 ]


In [3]:
# 2d array indexing
arr2

array([[ 1.  ,  1.1 , -5.45,  3.2 ],
       [-0.5 ,  0.33, 10.12, -5.  ]])

In [4]:
arr2[0]

array([ 1.  ,  1.1 , -5.45,  3.2 ])

In [5]:
arr2[0][1]

np.float64(1.1)

In [6]:
arr2[0,1]

np.float64(1.1)

In [7]:
arr2[0,:3]

array([ 1.  ,  1.1 , -5.45])

In [8]:
arr2[:,:3]

array([[ 1.  ,  1.1 , -5.45],
       [-0.5 ,  0.33, 10.12]])

In [9]:
list2[:,:3]

TypeError: list indices must be integers or slices, not tuple

In [10]:
arr2[:,[1,3,-1]]

array([[ 1.1 ,  3.2 ,  3.2 ],
       [ 0.33, -5.  , -5.  ]])

## Boolean Indexing

In [11]:
mask=arr1>0
mask

array([ True,  True, False,  True])

In [12]:
arr1[mask]

array([1. , 1.1, 3.2])

In [13]:
arr2[[True,False],:2]

array([[1. , 1.1]])

In [14]:
arr2

array([[ 1.  ,  1.1 , -5.45,  3.2 ],
       [-0.5 ,  0.33, 10.12, -5.  ]])

In [15]:
mask = arr2 < 0
mask

array([[False, False,  True, False],
       [ True, False, False,  True]])

In [16]:
arr2[mask]

array([-5.45, -0.5 , -5.  ])

In [17]:
arr2[mask]=0
arr2

array([[ 1.  ,  1.1 ,  0.  ,  3.2 ],
       [ 0.  ,  0.33, 10.12,  0.  ]])

In [20]:
list2 = [[1,1.1,-5.45,3.2],[-0.5,0.33,10.12,-5]]
arr2 = np.array(list2)
print(arr2)
print(arr2.shape)

[[ 1.    1.1  -5.45  3.2 ]
 [-0.5   0.33 10.12 -5.  ]]
(2, 4)


In [22]:
mask = arr2 > 6
mask


array([[False, False, False, False],
       [False, False,  True, False]])

In [24]:
arr2[mask]

array([10.12])

In [25]:
monty = [
    "spam", "spam", "spam", "spam",
    "bacon", "eggs", "sausage",
    "eggs", "cereal", "spam"
]

items, counts = np.unique(monty, return_counts=True)

hist = dict(zip(items, counts))
print(hist)

{np.str_('bacon'): np.int64(1), np.str_('cereal'): np.int64(1), np.str_('eggs'): np.int64(2), np.str_('sausage'): np.int64(1), np.str_('spam'): np.int64(5)}
