# Numpy Arrays

In [1]:
# 1d array
import numpy as np 

list1 = [1,1.1,-5.45,3.2]
arr1 = np.array(list1)
arr1

array([ 1.  ,  1.1 , -5.45,  3.2 ])

In [2]:
# 2d array
list2 = [[1,1.1,-5.45,3.2],[-0.5,0.33,10.12,-5]]
arr2 = np.array(list2)
arr2

array([[ 1.  ,  1.1 , -5.45,  3.2 ],
       [-0.5 ,  0.33, 10.12, -5.  ]])

In [3]:
arr1.shape

(4,)

In [4]:
arr2.shape

(2, 4)

# Basic Operations
- Operations between equal-size arrays or arrays and scalars operate element-wise
- Boolean operations on arrays also act element-wise
- No loops needed

In [6]:
# numpy makes array - scalar operations easier
list1-5

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [7]:
# using lists: very clunky loop
new_list1=[]
for x in list1:
    new_list1.append(x-5)
print (new_list1)

[-4, -3.9, -10.45, -1.7999999999999998]


In [8]:
list1

[1, 1.1, -5.45, 3.2]

In [9]:
arr1 - 5

array([ -4.  ,  -3.9 , -10.45,  -1.8 ])

In [10]:
# numpy makes array - array operations easier
list2*list2

TypeError: can't multiply sequence by non-int of type 'list'

In [11]:
arr2*arr2

array([[  1.    ,   1.21  ,  29.7025,  10.24  ],
       [  0.25  ,   0.1089, 102.4144,  25.    ]])

In [12]:
arr2

array([[ 1.  ,  1.1 , -5.45,  3.2 ],
       [-0.5 ,  0.33, 10.12, -5.  ]])

In [13]:
# numpy makes array - scalar boolean logic easier
list1 > 0

TypeError: '>' not supported between instances of 'list' and 'int'

In [14]:
# using lists: very clunky loop
is_pos=[]
for x in list1:
    is_pos.append(x>0)
is_pos

[True, True, False, True]

In [15]:
arr1 > 0

array([ True,  True, False,  True])

In [16]:
# numpy makes array - array boolean logic easier
arr1 = np.array([1,2,3,4])
arr2 = np.array([0,3,5,6])
arr1 > arr2

array([ True, False, False, False])

In [17]:
# numpy makes logical operations on boolean arrays easier
bool1 = (arr1 > 0) 
bool1

array([ True,  True,  True,  True])

In [18]:
bool2 = (arr1 > 1)
bool2

array([False,  True,  True,  True])

In [19]:
bool1 & bool2

array([False,  True,  True,  True])

In [20]:
bool1 | bool2

array([ True,  True,  True,  True])